[PLATFORM-1080]: Error handling (#157)
* Add dependencies for kafka and rabbit behind features

* Refactor Makefile.toml; add feature tests, lint etc

* Put sql under postgres feature. Compilation error otherwise

* Add rabbit module in event_bus

* Rabbit event bus implementation: WIP

* Add kafka implementation

* Add docker compose to test kafka and rabbit stuff

* Now rabbit and kafka get a config in order to be build

* Refactor error; not requested doesn't mean an error

* WIP moving integration tests to dedicated folder pt1

* Add more tests for manager

* WIP testing rabbit stuff

* WIP trying to let kafka tests work..

* Fix tests

* Remove kafka-ui container from compose

* Regen drone.yml with rabbit, kafka and zookeeper

* Regen drone.yml

* Uncomment routing key set in rabbit eb

* Add shared_view example

* Fix some tests; add tests for builder

* Other changes in shared_view example

* add eventual persistent and transactional views examples

* Fix warnings

* Wip on examples

* Event handler must be cloneable; change builder apis

* Completed saga example

* Some other examples

* Remove examples dbg; small changes

* Store crud example

* remove expect for unwrap in examples

* Locking strategies with showcase

* Rebuilder + rebuild example

* Update docker rust version to 1.69.0

* Rebuilder + multi aggregate rebuild

* Add rebuilder feature; change locking_strategies example with assertions

* Run clippy over examples

* Kafka and Rabbit example

* regenerate

* Review cpiemontese (grammar-fixes)

* Renaming some files

* WIP ok, everything works.. trying to improved types

* Small refactor trying to put type alias for transactional event handler

* Simplify aggregate manager error

* Remove commented deref for aggregate

* Remove Clone from Aggregate::State assoc type

* Remove Sync from Aggregate::Event

* Remove Send from Aggregate::Event

* Remove Send from Aggregate::Command

* Remove Send from Aggregate::State

* Remove 'static in favor of for<'a> lifetime bound

* Aggregate::Error should't be std::error::Error; tokio RwLock for handlers

* Update documentation

* Remove useless/wrong comments

* Some more on docs

---------

Co-authored-by: Cristiano Piemontese <cristiano.piemontese@prima.it>